version: '3'

services:
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    cap_add:
      - SYS_NICE
    volumes:
      - ./db/mysql-init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./db/data:/var/lib/mysql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
        ["./wait-for-it.sh", "db:3306", "--", "python", "pymysql_conn.py"]
